# Copyright 2026 BitWise Media Group Ltd
# SPDX-License-Identifier: MIT
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno.yaml
  - kyverno-policies.yaml
  - cert-manager.yaml
  - cert-manager-issuers.yaml
  - external-dns.yaml
  - gateway.yaml
  - patchy.yaml
  # - otel-collector.yaml
