# Copyright 2026 BitWise Media Group Ltd
# SPDX-License-Identifier: MIT
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-accounts.yaml
  - static-context.yaml
  - input-provider.yaml
  - resourceset.yaml
  - resourceset-health-check.yaml
  - resourceset-secrets.yaml
